server:
  port: 8083


debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.study.projectboardprac : debug
    org.springframework.web.servlet : debug
    org.hibernate.type.descriptor.sql.BasicBinder : trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article_test
    username: chorok
    password: chorok
#    url : jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver

  jpa:
    # ???? ??? ??? ??? ??
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    #open-in-view : false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enable : false
  sql.init.mode : always
  data.rest:
    base-path: /api
    detection-strategy : annotated
---
#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName : org.h2.Driver
#  sql.init.mode : always
#  test.database.replace : none

